---
title: "BIOINF703 Lab 1"
author: "Badi James"
date: "August 7, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(network)
library(sna)
source("networkLabHelper.R")
G <- readGraphFromFile("labNet.txt")
```

## Plotting G


```{r plottingG}
plot.network(G, usearrows =TRUE, mode = "kamadakawai")
```

## Plotting degree



```{r degree}
gNodeDegs <- degree(G, gmode = "graph")
hist(gNodeDegs)

```

## Binomial 

```{r binomial}
gDegMean <- mean(gNodeDegs)
n <- length(gNodeDegs)
prob <- gDegMean / (n-1)
binomDegs <- rbinom(n, n-1, prob)
hist(binomDegs)

```

## scale free degree

```{r scalefree}
k = 2:(n-1)
gam <- 1
plot(k,k^(-gam),ylab = "unnormalized density",
     main = paste("Power-law distribution with gamma =",gam))
```

```{r scalefree2}
gam <- 2
plot(k,k^(-gam),ylab = "unnormalized density",
     main = paste("Power-law distribution with gamma =",gam))
```

```{r scalefree3}
gam <- 3
plot(k,k^(-gam),ylab = "unnormalized density",
     main = paste("Power-law distribution with gamma =",gam))
```

## Making 200 ER graphs

```{r 200ER Betweenness}
er200 <- sapply(rep(n, 200), function(x) list(sampleER(x, prob)))
er200Btwn <- sapply(er200, betweenness, gmode = "graph", cmode = "undirected")
er200MeanBtwn <- apply(er200Btwn, 2, mean)
gBetween <- betweenness(G, gmode = "graph", cmode = "undirected")
gMeanBtwn <- mean(gBetween)
hist(er200MeanBtwn)
abline(v = gMeanBtwn, col = "red")
```

```{r 200ER degree centrality}
er200DegCen <- sapply(er200, degree, gmode = "graph")
er200MeanDegCen <- apply(er200DegCen, 2, mean)
gDegCen <- degree(G, gmode = "graph")
gMeanDegCen <- mean(gDegCen)
hist(er200MeanDegCen)
abline(v = gMeanDegCen, col = "red")

```

```{r 200ER local clustering coefficient}
```